### ISSUE TITLE
lib.stream() not promisified [v 0.2.1]

### ISSUE THREAD

**Issue by flotob** [inukshuk/zotero-node#1]
Hey,

first of all thanks for your great npm package!!

You mention in your readme that `lib.stream()` would also deliver a promise if zotero was promisified before hand via `zotero.promisify(Promise.promisify.bind(Promise)); // make zotero use promises instead of callbacks`.

Despite that, it stays with the callback patttern when i test this behavior `lib.stream(err, callback)`

Any idea?

Thanks. F

**Comment by inukshuk** [comment]
You can (in theory) use the stream object to send requests to the stream server (you won't have to, really, but it is something we considered to use in the original stream API) -- those requests use promises. I did not, in the end, promisify the `lib.stream` because it already returns a stream object and you do not need to use the callback at all. For example:

```
lib
 .stream()
 .on('topicUpdated', updated)
 .on('error', failed)
```

The stream is returned immediately so everything you would want to do with the stream object inside the callback (or when the promise resolves) you can do right away so I didn't see the point adding the extra promise. But I might have missed a use case where the extra promise would be useful.

**Comment by flotob** [comment]
Hey, thanks, that explains it!
